
target "SMRNetworkDemo" do
    platform:ios, '8.0'
    use_frameworks!
    inhibit_all_warnings!
    
    pod 'AFNetworking', '3.2.1', :inhibit_warnings => true
    
    post_install do |installer|
        installer.pods_project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['ENABLE_BITCODE'] = 'NO'
            end
        end
    end
end
